<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf3eecd2929a85c5753f0586162ab8be3
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'Brick\\Geo\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Brick\\Geo\\' => 
        array (
            0 => __DIR__ . '/..' . '/brick/geo/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf3eecd2929a85c5753f0586162ab8be3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf3eecd2929a85c5753f0586162ab8be3::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf3eecd2929a85c5753f0586162ab8be3::$classMap;

        }, null, ClassLoader::class);
    }
}
